### PR TITLE
feat(PageHeader): migrate CPE PageHeader

### PR DESCRIPTION
**Pull request by MaxHam**
this PR includes:
- experimental styles for page header
- addition of themes to the storybook
- addition of status tokens to the storybook
- docs for experimental page header
- addition of infrastructure to add custom font tokens
 - @CharlieOrlando please take a look at this, should we do it this general or should I just change the token in place and remove the infrastructure ?

### CODE REVIEW

**Comment by MaxHam** [comment]
have read the DCO document and I hereby sign the DCO.

**Comment by MaxHam** [comment]
recheck

**Comment by CharlieOrlando** [comment]
that all looks good to me. you want me to merge it or are you still working on it?

**Comment by CharlieOrlando** [comment]
honestly, great work, dude. thanks for setting up the themes!

**Comment by MaxHam** [comment]
@CharlieOrlando thank you !
I need to integrate the translations for page header and then we can merge it.

**Comment by MaxHam** [comment]
Ok, please review it another time @CharlieOrlando. I added a translation item and unit tests for the new styles.

**Comment by MaxHam** [comment]
Hi @CharlieOrlando , are you ok with me merging this PR ?

**Pull request merged**
